### ISSUE TITLE
Not supported 2023.2

### ISSUE THREAD

**Issue by v1ack** [WhiteMemory99/Intellij-Python-Inlay-Params#33]

**Comment by bendathierrycom** [comment]
Hello,

I have this error message as a notification in Intellij Idea Ultimate : 

`Plugin 'Python Inlay Params' (version '0.3.2') is not compatible with the current version of the IDE, because it requires build 231.* or older but the current build is IU-232.8660.185.`

Seems to be a bad version checking in place.

**Comment by FieryDruid** [comment]
@v1ack 
@bendathierrycom 

Try this

[Python.Inlay.Params-0.3.3.zip](https://github.com/WhiteMemory99/Intellij-Python-Inlay-Params/files/12266770/Python.Inlay.Params-0.3.3.zip)

`Settings -> Plugins -> <Gear icon> -> Install Plugin from disk...` and select .zip archive

**Comment by v1ack** [comment]
Yes, it works, thanks

**Comment by Ayfri** [comment]
Why not releasing an update ?

**Comment by WhiteMemory99** [comment]
2023.2 support is out. 1-2 days until the marketplace version is approved by JetBrains

**Comment by bendathierrycom** [comment]
Thanks few months later. Have a good 2024 year too.
